name: Feature Request
description: Ask for a new feature request
# title: " "
labels: [feature-request]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for adding this feature request!

  - type: textarea
    attributes:
      label: description
      description: Please write a short description of your request.
      placeholder: |
        What would you like to see in this app?
    validations:
      required: true

  - type: textarea
    attributes:
      label: use-cases
      description: |
        Describe your feature request. Be as coherent as you can.
      placeholder: |
        What are the use cases of this feature? How would it improve the app

  - type: textarea
    attributes:
      label: additional-information
      description: Any additional information that might be helpful
